# Generated by Django 4.0.4 on 2022-05-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(help_text='the name for counselor', max_length=50)),
                ('last_name', models.CharField(help_text='the name for counselor', max_length=50)),
                ('start_date', models.DateField()),
                ('expertise_field', models.CharField(max_length=50)),
                ('statment', models.TextField(max_length=240)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
