# Generated by Django 4.0.4 on 2022-05-28 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='the name for counselor', max_length=50)),
                ('last_name', models.CharField(help_text='the last for counselor', max_length=50)),
                ('start_date', models.DateField()),
                ('expertise_field', models.CharField(max_length=50)),
                ('statment', models.TextField(max_length=240)),
                ('image', models.ImageField(upload_to='images/')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name for clint', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('boday', models.TextField(max_length=240)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ShawerApp.counselor')),
            ],
        ),
    ]
