# Generated by Django 4.0.4 on 2022-05-28 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShawerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='boday',
            new_name='body',
        ),
    ]
