# Generated by Django 4.0.4 on 2022-05-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShawerApp', '0002_rename_boday_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='profile',
        ),
    ]
