# Generated by Django 4.0.4 on 2022-05-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShawerApp', '0003_rename_post_comment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(),
        ),
    ]
