# Generated by Django 4.0.4 on 2022-05-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShawerApp', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='التعليق'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
    ]
